package com.cpe.backend.Doctororder.repository;

import java.util.Collection;

import com.cpe.backend.Doctororder.entity.DoctorOrder;
import com.cpe.backend.Examination.entity.ExaminationSystem;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;  
  
@RepositoryRestResource
public interface DoctorOrderRepository extends JpaRepository<DoctorOrder, Long> {
    DoctorOrder findById(long id);

    // DoctorOrder findByExaminationId(ExaminationSystem id);

    @Query(value = "SELECT DOCTORORDER.DOCTORORDER_ID ,  EXAMINATION_SYSTEM .PATIENT_ID  ,DOCTORORDER .DATE ,DOCTORORDER .PRESCRIPTION_NUMBER,DOCTORORDER .ALLERGIES  ,DOCTORORDER .REACTION,MEDICINE .MNAME  ,MEDICATION_TYPE .TYPE_NAME   FROM MEDICINEITEM left join DOCTORORDER on DOCTORORDER.DOCTORORDER_ID =MEDICINEITEM.DOCTOR_ORDER_ID left join MEDICINE on MEDICINE.MEDICINE_ID =MEDICINEITEM.MEDICINE_ID left join MEDICATION_TYPE on MEDICATION_TYPE .MEDICATION_TYPE_ID =MEDICINEITEM.MEDICATION_TYPE_ID left join EXAMINATION_SYSTEM on EXAMINATION_SYSTEM.EXAMINATION_SYSTEM_ID  =DOCTORORDER.EX_EXAMINATION_SYSTEM_ID where EXAMINATION_SYSTEM.PATIENT_ID = :PATIENT_ID"
    ,
     nativeQuery = true)
     Collection<Object[]> findByNationalId(@Param("PATIENT_ID") long PATIENT_ID);

    

    @Query(value ="SELECT *FROM DOCTORORDER WHERE DOCTORORDER .EX_EXAMINATION_SYSTEM_ID  = :Ex"
    ,
     nativeQuery = true)
    DoctorOrder findByExaminationSystemId(@Param("Ex") long ex);

    @Query(value ="SELECT DOCTORORDER.DOCTORORDER_ID  ,  EXAMINATION_SYSTEM .PATIENT_ID  ,DOCTORORDER .DATE ,DOCTORORDER .PRESCRIPTION_NUMBER,EXAMINATION_SYSTEM .SYMPTOM ,DOCTORORDER .ALLERGIES  ,DOCTORORDER .REACTION,MEDICINE .MNAME  ,MEDICATION_TYPE .TYPE_NAME,DOCTOR .DNAME    FROM MEDICINEITEM left join DOCTORORDER on DOCTORORDER.DOCTORORDER_ID =MEDICINEITEM.DOCTOR_ORDER_ID  left join MEDICINE on MEDICINE.MEDICINE_ID =MEDICINEITEM.MEDICINE_ID left join MEDICATION_TYPE on MEDICATION_TYPE .MEDICATION_TYPE_ID =MEDICINEITEM.MEDICATION_TYPE_ID left join EXAMINATION_SYSTEM on EXAMINATION_SYSTEM.EXAMINATION_SYSTEM_ID  =DOCTORORDER.EX_EXAMINATION_SYSTEM_ID left join DOCTOR  on EXAMINATION_SYSTEM .EXAMINATION_SYSTEM_ID = DOCTOR .DOCTORS_ID where DOCTORORDER.PRESCRIPTION_NUMBER = :prescription_number"
    ,
     nativeQuery = true)
     Collection<Object[]> findByPrescriptionNumber(@Param("prescription_number") String prescription_number);

     
    

    // SELECT do.DOCTORORDER_ID,do.date , do.allergies,do.reaction,do.prescription_number,p.name , e.SYMPTOM , md.Mname , mt.TYPE_NAME,d.Dname  FROM MEDICINEITEM as m INNER JOIN DOCTORORDER as do  INNER JOIN PATIENT as p INNER JOIN  EXAMINATION_SYSTEM as e INNER JOIN MEDICINE as md INNER JOIN  Medication_Type as mt INNER JOIN DOCTOR as d on do. DOCTORORDER_ID = m.MEDICINEITEM_ID and e.PATIENT_ID = p.NATIONAL_ID and m.MEDICINE_ID = md.MEDICINE_ID and m. MEDICATION_TYPE_ID = mt. MEDICATION_TYPE_ID  and do.EX_EXAMINATION_SYSTEM_ID = e.EXAMINATION_SYSTEM_ID and d.DOCTORS_ID = e.DOCTOR_ID where DOCTORORDER_ID = :id

   
//     _____แบบกำหนด id _____________

//  SELECT do.DOCTORORDER_ID,do.date , p.name , e.SYMPTOM , md.Mname , mt.TYPE_NAME,d.Dname   FROM MEDICINEITEM as m INNER JOIN DOCTORORDER as do  INNER JOIN PATIENT as p INNER JOIN  EXAMINATION_SYSTEM as e INNER JOIN MEDICINE as md INNER JOIN  Medication_Type as mt INNER JOIN DOCTOR as d on do. DOCTORORDER_ID = m.MEDICINE_ITEM and e.PATIENT_ID = p.NATIONAL_ID and m.MEDICINES_ID = md.MEDICINE_ID and m. MEDICATION_TYPE_ID = mt. MEDICATION_TYPE_ID  and do.EX_EXAMINATION_SYSTEM_ID = e.EXAMINATION_SYSTEM_ID and d.DOCTORS_ID = e.DOCTOR_ID where DOCTORORDER_ID = ?
// _____________แบบมาทั้งหมด__________________________
//  SELECT do.DOCTORORDER_ID,do.date , p.name , e.SYMPTOM , md.Mname , mt.TYPE_NAME,d.Dname   FROM MEDICINEITEM as m INNER JOIN DOCTORORDER as do  INNER JOIN PATIENT as p INNER JOIN  EXAMINATION_SYSTEM as e INNER JOIN MEDICINE as md INNER JOIN  Medication_Type as mt INNER JOIN DOCTOR as d on do. DOCTORORDER_ID = m.MEDICINE_ITEM and e.PATIENT_ID = p.NATIONAL_ID and m.MEDICINES_ID = md.MEDICINE_ID and m. MEDICATION_TYPE_ID = mt. MEDICATION_TYPE_ID  and do.EX_EXAMINATION_SYSTEM_ID = e.EXAMINATION_SYSTEM_ID and d.DOCTORS_ID = e.DOCTOR_ID
// _______
    
//     SELECT do.DOCTORORDER_ID,do.date , p.name , e.SYMPTOM , md.name , mt.TYPE_NAME,d.name   FROM MEDICINEITEM as m
// INNER JOIN DOCTORORDER as do  
// INNER JOIN PATIENT as p
// INNER JOIN  EXAMINATION_SYSTEM as e
// INNER JOIN MEDICINE as md
// INNER JOIN  Medication_Type as mt
// INNER JOIN DOCTOR as d
// on do. DOCTORORDER_ID = m.MEDICINE_ITEM and
//  e.PATIENT_ID = p.NATIONAL_ID 
//  and m.MEDICINES_ID = md.MEDICINE_ID 
// and m. MEDICATION_TYPE_ID = mt. MEDICATION_TYPE_ID  
// and do.EX_EXAMINATION_SYSTEM_ID = e.EXAMINATION_SYSTEM_ID
// and d.DOCTOR_ID = e.DOCTOR_ID
// SELECT do.DOCTORORDER_ID,do.date , p.name , e.SYMPTOM , md.name , mt.TYPE_NAME,d.name   FROM MEDICINEITEM as m INNER JOIN DOCTORORDER as do  INNER JOIN PATIENT as p INNER JOIN  EXAMINATION_SYSTEM as e INNER JOIN MEDICINE as md INNER JOIN  Medication_Type as mt INNER JOIN DOCTOR as d on do. DOCTORORDER_ID = m.MEDICINE_ITEM and e.PATIENT_ID = p.NATIONAL_ID and m.MEDICINES_ID = md.MEDICINE_ID and m. MEDICATION_TYPE_ID = mt. MEDICATION_TYPE_ID  and do.EX_EXAMINATION_SYSTEM_ID = e.EXAMINATION_SYSTEM_ID and d.DOCTOR_ID = e.DOCTOR_ID"
   

}